import = [
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml",
]
live_config_reload = true
[shell]
program = "/bin/zsh"
[window]
opacity = 0.64
decorations = "None"
startup_mode = "Maximized"
[font]
normal = {family = "Fira Code Nerd Font Mono", style = "Retina,Regular"}
bold = {family = "Fira Code Nerd Font Mono", style = "Bold"}
italic = {family = "Source Code Pro", style = "Italic"}
bold_italic = {family = "Source Code Pro", style = "Bold Italic"}
size = 16
